//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public Expense()
        {
            this.BudgetCategories = new HashSet<BudgetCategory>();
        }
    
        public System.Guid id { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<BudgetCategory> BudgetCategories { get; set; }
    }
}
